#!/bin/sh



###########
# OPENVPN #
###########

# check to see if openvpn files exist
if [ ls /vpn/*.ovpn 1>/dev/null 2>&1 ]; then
  # start openvpn 
  cd /vpn
  openvpn --config *.ovpn &

  # change dns to google's dns server
  echo "nameserver 8.8.8.8" > /etc/resolv.conf

  # route all traffic through vpn
  sleep 20
  IP=`/sbin/ifconfig tun0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`
  ip route replace 0.0.0.0/0 via $IP
fi


############
# rTorrent #
############

# determine if a configuration file is present in /config/ and use it for
# rtorrent. If there isn't, then just use the default config file packaged
# with this container
if [ -f /root/.rtorrent.rc ]; then
  # we will remove the config file by default
  rm /root/.rtorrent.rc
fi

if [ -f /config/rtorrent.rc ]; then
  # check if /config/rtorrent.rc is present. use over preferent to
  # /config/.rtorrent.rc
  ln -s /config/rtorrent.rc /root/.rtorrent.rc

elif [ -f /config/.rtorrent.rc ]; then
  # check if /config/.rtorrent.rc exists
  ln -s /config/.rtorrent.rc /root/.rtorrent.rc

elif [ -d /config ]; then
  # if the /config/ directory is there but no config file in there, copy
  # over a default config file for reference
  cp /root/rtorrent_config /config/rtorrent.rc
  ln -s /config/rtorrent.rc /root/.rtorrent.rc

else
  # use the default /root/rtorrent_config file
  ln -s /root/rtorrent_config /root/.rtorrent.rc
fi

# remove session block
rm -rf /root/.session/rtorrent.lock

############
# htpasswd #
############

# the goal here is to have basic authentication
# using simple htpassword file. First we check if
# the file exists and add the necessary directives to the httpd file
if [ -f /config/password_file ]; then
  # backup copy of lighttpd.file
  if [ ! -f /etc/lighttpd/lighttpd.confg ]; then
    cp /etc/lighttpd/lighttpd.confg /etc/lighttpd/lighttpd.confg.bak
  fi

  # enable the mod_auth module
  sed -ie 's/#[ ]*"mod_auth/"mod_auth/g' /etc/lighttpd/lighttpd.conf

  # set the password protection directives
  sed -ie 's/# auth.backend[ ]/auth.backend /g' /etc/lighttpd/lighttpd.conf
  sed -ie 's/# auth.backend.plain.userfile = ".*"/auth.backend.plain.userfile = \"\/config\/password_file\"/g' /etc/lighttpd/lighttpd.conf

  # need to set the directives stating that a specific
  # directory requires password auth as mentioned in
  #http://www.cyberciti.biz/tips/lighttpd-setup-a-password-protected-directory-directories.html  
fi



############
# starting #
############

# start webserver
lighttpd -f /etc/lighttpd/lighttpd.conf

# start rtorrent
rtorrent
